### ISSUE TITLE
i18n/l10n support

### ISSUE THREAD

**Issue by CuloArdido** [Zeal-Operating-System/ZealOS#117]
I think this project could reach more people if it were available in languages other than English. To start with, how viable would it be to do something like this? Maybe porting [gettext](https://en.wikipedia.org/wiki/Gettext) to ZealC?

**Comment by xslendix** [comment]
I do not think localisation should be a primary concern for the project. Not only do you have to rewrite most code that uses strings, add support for unicode and create a brand new font with thousands of characters, a localisation system also needs to be put in place and some way to load all the strings from a huge amount of files. This would absolutely positively break the line count limit and is not feasible in any realistic amount of time to be implemented. Most people are going to know English either way because HolyC and functions are in English.

**Comment by GutPuncher** [comment]
https://zeal-operating-system.github.io/Doc/Charter.DD.html

Zeal's Charter (in the context of the OS font) specifies:
> * Just one 8x8 fixed-width font. No Unicode, just Extended ASCII. Other countries can make their own versions. The versions 
should be just for one language and platform.

The precedence this sets for localization-related changes to Zeal is that each version of Zeal is localized on a country/region basis.

The standard ZealOS repository has English localization. To localize the entire OS for another country/region, the correct procedure is to fork the OS and maintain a localized fork, which would have changes merged into it automatically/manually from the main repository.
