### ISSUE TITLE
is booting with QEMU really supported? (help)

### ISSUE THREAD

**Issue by coloredmarble** [Zeal-Operating-System/ZealOS#157]
Sorry to be that type of idiot that tries to do something in an unsupported way. but not ***QEMU***?? no frickin way.  
The current issue is that ZealOS won't detect the boot cdrom supplied to QEMU. Saying it cannot `"Detect the ATAPI Boot drive"`  

```
# current supplied commands
qemu-system-x86_64 -m 512M -enable-kvm -drive file=zeal.iso,format=raw,index=0,media=disk \
-device ahci,id=ahci \
-display sdl
```  
I've also tried to look up anything related to QEMU and ATAPI. and i found this old page on the [wiki](https://wiki.qemu.org/Features/IDE)

It appears that ATAPI support is yet to be added (since almost a decade ago). Or this page might be outdated. and ATAPI support is already out. but i don't know how to use it.

Is QEMU really unsupported? even though it can boot TempleOS just fine?

**Comment by y4my4my4m** [comment]
@coloredmarble 

This works for me on the latest ISO, using qemu 8.2.2

`qemu-system-x86_64 -display gtk,gl=on,zoom-to-fit=on -machine q35,kernel_irqchip=on,accel=kvm -audiodev driver=pa,id=pa1 -cdrom ZealOS-PublicDomain-BIOS  -*.iso -device AC97,audiodev=pa1 -hda ZealOS.qcow2 -m 8G -smp $(nproc) -rtc base=localtime -nic user,model=pcnet`

The QEMU uasge documentation and implementation itself is a bit rough because qemu keeps changing and removing legacy stuff (like they did from version 8)

**Comment by GutPuncher** [comment]
@coloredmarble  https://zeal-operating-system.github.io/ZealOS-wiki/Installing-(QEMU)

**Comment by GutPuncher** [comment]
Assuming issue was resolved after 2 month stale, setting inactive
