### ISSUE TITLE
How do you export code?

### ISSUE THREAD

**Issue by sugkiy** [Zeal-Operating-System/ZealOS#2]
I know you could burn an ISO image in TempleOS, but it doesn't really work(doesn't ouput to disk file). Should I use special commands for this?
Also how do you build the ISO of this?

**Comment by sugkiy** [comment]
Could you change the screen resolution while installing? It defaults to 1366x768 and skips the chossing step,

**Comment by TomAwezome** [comment]
> You can increase the resolution by going to System/Boot and running BootHDIns. You run it iirc with BootHDIns(); or #include BootHDIns; One of those two should work.

`BootHDIns;` has the same effect when run in any directory on a drive. All that is needed is to type `BootHDIns;` and Enter at the command line. It will guide you through recompiling the kernel, and choosing a video resolution is one of the last parts of this process. For more details, check here: https://github.com/Zeal-Operating-System/ZealOS/wiki/Kernel-Recompiling-(Standard) 

> I know this is against the Charter, but has anyone succeeded using HGBD?
The ZealOS Charter mainly applies to first-party code, meaning simply that any third-party libraries are not supported or tested. I haven't heard of anybody trying to use HGBD with ZealOS, but it's possible it might work.

**Comment by TomAwezome** [comment]
> Just one more question: I tried to mount an .ISO.C image from the web, but ZealOS just said unknown filesystem. Did I do wrong on mounting the disk on Virtualbox or am I wrong with Cd("T:");?

Using discs can be a bit tricky. Typically the best bet is use the `Mount;` function and process to mount the ATAPI drive, then use `DiskChange('t');` to go to the disc. Sometimes it's finicky and might need another `DiskChange('t');` run to update the drive's state and properly initialize the disc to read data off it. ZealOS has support for TempleOS, ZenithOS, and ZealOS RedSea ISOs, so most ISO.C disc files should be readable.

**Comment by z0mbieslayer** [comment]
> ZealOS has support for TempleOS, ZenithOS, and ZealOS RedSea ISOs, so most ISO.C disc files should be readable.
Sorry to reopen this, but would would there be a way to run the contents of the TempleOS Supplemental discs despite them being HC and not ZC? Namely looking for After Egypt. Tried to run it and forgot it was a different extension.

**Comment by doodayev** [comment]
There is a code converter in C:/System/Utilities called ConversionScript.ZC
Include the function and then call the function with the directory or files you have in mind. If it doesn't work, then some things need to be updated. Please show what error message you get if you do.

**Comment by z0mbieslayer** [comment]
Not sure if I'm doing it right or not, but I'm getting an Undefined identifier error. This is after I've included it.

**Comment by doodayev** [comment]
Post a screenshot so I can see the full error

**Comment by z0mbieslayer** [comment]
![zealos](https://github.com/Zeal-Operating-System/ZealOS/assets/44008070/9a5d0902-18eb-4cf4-8271-2b14ef4277db)

**Comment by z0mbieslayer** [comment]
![zealos](https://github.com/Zeal-Operating-System/ZealOS/assets/44008070/9b4e42f1-4d55-4ea5-a331-d39f04d6f65a)

**Comment by doodayev** [comment]
Oh right. There's a problem. For some reason most files in TempleOS are compressed. Make sure that you save the source code as ONLY .HC and not .HC.Z
That Z at the end means that it's compressed. There's other problems with the way you're doing it so let me give it a shot and demonstrate how it's supposed to go.
Wait a bit

**Comment by doodayev** [comment]
![HowToConvertFromHolyCToZeal](https://github.com/Zeal-Operating-System/ZealOS/assets/61427449/8a0c284c-39a2-4966-8bdc-b08900ec3ba5)
Alright here's a guide on how to do it.

**Comment by doodayev** [comment]
[AfterEgypt.zip](https://github.com/Zeal-Operating-System/ZealOS/files/12581406/AfterEgypt.zip)
And here's my upload of AfterEgypt in case you don't want to uncompress the files yourself.

**Comment by z0mbieslayer** [comment]
> [AfterEgypt.zip](https://github.com/Zeal-Operating-System/ZealOS/files/12581406/AfterEgypt.zip) And here's my upload of AfterEgypt in case you don't want to uncompress the files yourself. (Unfortunately it doesn't work even after converting successfully. Not sure why yet)

Thanks for the help, a shame it doesn't work just like that.

**Comment by GutPuncher** [comment]
It would be helpful if there were compression/decompression tools for TOS .Z, Windows/Linux .zip, Linux .tar.gz, etc., implemented as a third-party program that could be transferred to the https://github.com/Zeal-Operating-System/ organization among the other supported non-standard programs.

ZealOS removes compression entirely to make all files as transparent as possible, and to save CPU time spent on decompressing/re-compressing that isn't necessary as space/speed via AHCI on modern drives is enough to negate the need for compression. However, there are use-cases for having an extra optional tool for it, e.g. uncompressing and converting TOS programs, downloading and unzipping files downloaded via FTP and reuploading compressed, unzipping `master.zip` repo .ZIP clones within the OS, or unzipping compressed files downloaded via Gopher. 

Additionally, the ConversionScript is very minimal, and is basically just a find-and-replace. It doesn't handle situations like the many API differences between TOS and Zeal that will cause compiler errors. It would also be helpful for porting if the script was more integrated and aware of Zeal's API changes, so that it can automatically revise function calls/suggest specific changes.
