### ISSUE TITLE
Dollar sign causes EOF?

### ISSUE THREAD

**Issue by sugkiy** [Zeal-Operating-System/ZealOS#4]
![image](https://user-images.githubusercontent.com/90227297/139618377-1cd357df-5f1f-44ca-89e8-da9175b940a2.png)
If there is a single dollar sign in a file, Ed() seems to just cut the file. I don't knowif this is expected behavior.
![image](https://user-images.githubusercontent.com/90227297/139618535-3f0d9c9d-a104-41e0-a9de-8789bdedd639.png)

![image](https://user-images.githubusercontent.com/90227297/139618598-ebc5f200-f7ff-43fd-82e0-593269523d43.png)
If I put two dollar signs, then the machine shows it as one dollar sign.
![image](https://user-images.githubusercontent.com/90227297/139618675-9af04210-029a-4511-b98b-f4c468973b5a.png)

**Comment by TomAwezome** [comment]
A single dollar sign, in DolDoc syntax, is an escape character, recognized as the beginning of a DolDoc tag. An example is `$GREEN$`, which is a DolDoc tag that sets the current foreground text color to green. If you type a dollar sign in a document, type another one to make it a double-dollar-sign, which DolDoc recognizes and prints as a standard character, instead of as DolDoc syntax. DolDoc tags won't be visible when viewing a document because they affect how the document is drawn, they aren't drawn characters. To see the tags in a document, press `Ctrl-T`.
https://zeal-operating-system.github.io/ZealOS/Doc/DolDocOverview.DD.html
https://zeal-operating-system.github.io/ZealOS/Doc/CosmiC.DD.html#l240
If importing files that contain dollar signs, you can try opening them with the `Plain` function first, to view them as plain-text.

**Comment by sugkiy** [comment]
Oh, I get it. Thanks for the answer!

**Comment by sugkiy** [comment]
Can I ask another question? How do you use escape codes in TempleOS? Print("\x1b[2J"); doesn't seem to work..

**Comment by TomAwezome** [comment]
ANSI escape codes are not supported.

**Comment by sugkiy** [comment]
Then is there a command like clear?

**Comment by TomAwezome** [comment]
Yes, `$CL$` is a DolDoc tag that will clear the entire document, and the functions `Cls` and `DocClear` can be used clear the screen programmatically as well.

**Comment by TomAwezome** [comment]
As a note, you don't have to use `Print()` to print strings. Using raw quotes as a statement, such as `"Test:\n";` will print to the document. Also, there is a function `ToDolDoc` which can be used to duplicate dollar signs in a document to make it functional as DolDoc.
