### ISSUE TITLE
Is there scanf() of some kind?

### ISSUE THREAD

**Issue by sugkiy** [Zeal-Operating-System/ZealOS#6]
```holyc
for (i = 0; i < n; i++)
    for (j = 0; j < n; j++)
      scanf("%d", &G[i][j]);
```
I'd like to write something like this, but I can't really get input split by spaces. Is there a HolyC equivalent to this?

**Comment by doodayev** [comment]
Yes. Check in Demo/Prompt and you can find a small example of it.
For instance you want to get an integer from someone?

I64 Cheeseburgers;
Cheeseburgers=I64Get("How many cheeseburgers do you want? ", Cheeseburgers);
"You ordered %d cheeseburgers \n", Cheeseburgers;

You would format it like that. This code also would work if you entered an arithmetic expression instead of just an integer.

**Comment by TomAwezome** [comment]
F64Get, I64Get, StrGet, CharGet
