### ISSUE TITLE
Can't get mouse working on real machine.

### ISSUE THREAD

**Issue by Ccode-lang** [Zeal-Operating-System/ZealOS#70]
My machine has full support including the ps2 controller. However, my mouse does not work.

**Comment by TomAwezome** [comment]
What machine? What motherboard model? What mouse? Please provide more details. Thanks and have a good day

**Comment by TomAwezome** [comment]
After you've posted this information, please try a few different mice to see if any others work. Doing so will make it easier to find out what portions of the PS/2 code need revising.

**Comment by Ccode-lang** [comment]
the system I am using is an Inspiron 5348 all-in-one.  I have tried with both a Logitech keyboard (don't know the model) built-in trackpad and a raspberry pi 400 mouse, but neither work.

**Comment by Ccode-lang** [comment]
Now I have tried every mouse I own. Only keyboards work for some reason.

**Comment by TomAwezome** [comment]
Thank you for the system specs and testing!

When I look up "Inspiron 5348 all-in-one", I find results with pictures that show a computer that doesn't have PS/2 ports.
When I look up "raspberry pi 400 mouse", I find results for only USB mice.

ZealOS does not have any USB support, and is only able to use USB devices if the BIOS on your computer is kind enough to emulate PS/2 from USB internally. It appears your computer does not support this.

**Comment by Ccode-lang** [comment]
Oh, I thought that mine did support that translation.  Thanks for the info!

**Comment by TomAwezome** [comment]
Based on you mentioning keyboard working but mouse non-working, it's possible your computer may only be willing to emulate one of the two devices, or possible that it's emulating PS/2 mouse in a way Zeal isn't expecting. I recall the TinkerOS developer mentioning the PS/2 code expecting mouse with packet size of 3 and not supporting e.g. 4, but I don't remember how to make that change in the code, nor do I know if it's possible to support both packet types. Either way, in a situation with a computer with zero PS/2 ports, a USB implementation should be developed and a PR sent in to add USB keyboard and mouse support, rather than relying on getting lucky with a BIOS hack on modern systems.
